---
version: '2'

services:
  trafficserver:
    build: trafficserver-${CENTOS_VERSION}
    image: trafficserver:${CENTOS_VERSION}
    container_name: trafficserver-${CENTOS_VERSION}-${TS_VERSION}
    volumes:
      - ${PWD}/rpmbuild:/home/builder/rpmbuild:rw
    command: ['/usr/bin/scl','enable','devtoolset-8','rpmbuild -bb SPECS/trafficserver-${TS_VERSION}.spec']
