---
version: '2'

services:
  trafficserver:
    build: trafficserver-${CENTOS_VERSION}
    image: trafficserver:${CENTOS_VERSION}
    volumes:
      - ${PWD}/rpmbuild:/home/builder/rpmbuild:rw
    command: ['rpmbuild', '-bb' ,'SPECS/trafficserver-${TS_VERSION}.spec']

