---
version: '3.8'

services:
  trafficserver:
    build: trafficserver-${CENTOS_VERSION} 
    image: trafficserver:${CENTOS_VERSION}
    container_name: trafficserver-${CENTOS_VERSION}-${TS_VERSION}
    volumes:
      - ${PWD}/rpmbuild:/home/builder/rpmbuild:rw
    environment:
      - TS_VERSION=${TS_VERSION}
    command: ['rpmbuild','-bb','SPECS/trafficserver-${TS_VERSION}.spec']
    platform: "linux/amd64"
